[package]
name = "common"
edition.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
axum = { workspace = true }
serde = { workspace = true, features = ["derive"] }
validator = { workspace = true, features = ["derive"] }