[package]
name = "common"
edition.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
dotenvy = { workspace = true }
num_cpus = { workspace = true }
thiserror = { workspace = true }

