[package]
name = "common"
edition.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

